In [1]:
import random
import requests
from datetime import datetime
import time
import os
from dotenv import load_dotenv
import pandas as pd
load_dotenv()

ACCOUNT = os.getenv('STOCK_ACCOUNT_USERNAME')
PASSWORD = os.getenv('STOCK_ACCOUNT_PASSWORD')
PG_URI = os.getenv('POSTGRES_URI')
print(f"Loaded account: {ACCOUNT}")
print(f"Loaded password: {PASSWORD}")
print(f"Loaded PostgreSQL URI: {PG_URI}")

Loaded account: N76154340
Loaded password: 4340
Loaded PostgreSQL URI: postgresql+psycopg://admin:ats@postgres:5432/ats_db

In [2]:
from util_stock_info import *
Get_Stock_Informations(2330, "20260316", "20260316")

[{'date': 1773619200, 'capacity': '35017289.00000', 'turnover': '65021963085.00000', 'high': '1880.00000', 'low': '1845.00000', 'close': '1845.00000', 'change': '-20.00000', 'transaction_volume': 221241, 'stock_code_id': '2330', 'open': '1875.00000'}]

[{'date': 1773619200,
  'capacity': '35017289.00000',
  'turnover': '65021963085.00000',
  'high': '1880.00000',
  'low': '1845.00000',
  'close': '1845.00000',
  'change': '-20.00000',
  'transaction_volume': 221241,
  'stock_code_id': '2330',
  'open': '1875.00000'}]

In [3]:
Get_User_Stocks(ACCOUNT, PASSWORD)

[]

[]

In [4]:
stock_info = pd.read_json('http://140.116.86.242:8081/api/stock/get_stock_list')
stock_info.head()

    result                                               data
0  success  {'code': '0050', 'name': '元大台灣50', 'listing_ti...
1  success  {'code': '0051', 'name': '元大中型100', 'listing_t...
2  success  {'code': '0052', 'name': '富邦科技', 'listing_time...
3  success  {'code': '0053', 'name': '元大電子', 'listing_time...
4  success  {'code': '0054', 'name': '元大台商50', 'listing_ti...

In [5]:
pd.json_normalize(stock_info['data'][0])

   code    name  listing_time industry  type
0  0050  元大台灣50    1056902400              0

In [6]:
from FinMind.data import DataLoader

api = DataLoader()
# api.login_by_token(api_token='token')
df = api.taiwan_stock_info_with_warrant()
df.head()

2026-03-17 06:57:11.865 | INFO     | FinMind.data.finmind_api:login_by_token:84 - Login success
2026-03-17 06:57:11.866 | INFO     | FinMind.data.finmind_api:get_data:153 - download Dataset.TaiwanStockInfoWithWarrant, data_id:

  industry_category stock_id stock_name  type        date
0             封閉式基金     0001         鴻運  twse  2024-12-05
1             封閉式基金     0002         福元  twse  2024-12-05
2             封閉式基金     0003         成長  twse  2024-12-05
3             封閉式基金     0004         國民  twse  2024-12-05
4             封閉式基金     0005         成功  twse  2024-12-05

In [7]:
print(df['industry_category'].unique())

['封閉式基金' 'ETF' '上櫃ETF' '上櫃指數股票型基金(ETF)' '受益證券' 'ETN' '指數投資證券(ETN)'
 '認購權證(不含牛證)' '熊證(不含可展延熊證)' '牛證(不含可展延牛證)' '認售權證(不含熊證)' '可展延牛證' '水泥工業' '其他'
 '食品工業' '電器電纜' '農業科技業' '觀光事業' '觀光餐旅' '塑膠工業' '建材營造' '汽車工業' '電子零組件類' '紡織纖維'
 '貿易百貨' '運動休閒' '電子工業' '電子零組件業' '電機機械' '可轉換公司債' '生技醫療類' '電腦及週邊類' '運動休閒類'
 '化學生技醫療' '生技醫療業' '化學工業' '其他電子類' '玻璃陶瓷' '造紙工業' '鋼鐵工業' '居家生活' '橡膠工業' '航運業'
 '創新板股票' '創新版股票' '電腦及週邊設備業' '半導體業' '其他電子業' '通信網路業' '光電業' '電子通路業' '資訊服務業'
 '油電燃氣業' '數位雲端類' '金融保險' '居家生活類' '文化創意業' '光電業類' '半導體類' '綠能環保類' '通信網路類'
 '電子商務業' '數位雲端' '資訊服務類' '電子通路類' '綠能環保' '金融業' '認購售權證' '牛熊證(不含展延型牛熊證)'
 '油電燃氣類' '存託憑證']

In [8]:
df.to_sql(name='stock_info', con=PG_URI, if_exists='replace', index=False)

-1